export const data=[
  {
   id:1,
   img:'/images/html.webp',
   SkillName:"HTML",
   level:"Expert"
  },
  {
    id:2,
    img:"/images/css3.webp",
    SkillName:"Css",
    level:"Expert"
   },
   {
    id:3,
    img:"/images/bootstrap.webp",
    SkillName:"Bootstrap",
    level:"Expert"
   },
   {
    id:4,
    img:"/images/javascript.webp",
    SkillName:"JavaScript",
    level:"Intermediate"
   },
   {
     id:5,
     img:"/images/react.webp",
     SkillName:"React",
     level:"Intermediate"
    },
   
    {
      id:6,
      img:"/images/tailwind_css.webp",
      SkillName:"Tailwind",
      level:"Intermediate"
     },
     {
      id:7,
      img:"/images/git.webp",
      SkillName:"Git",
      level:"Intermediate"
     },
     {
      id:8,
      img:"/images/Figma.webp",
      SkillName:"Figma",
      level:"Intermediate"
     }
  
]